name: Android CI

on:
  push:
    branches:
      - '*'
      - '!master'
  pull_request:
    branches: [ master ]
    
jobs:
  lint_and_test:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Load config
        id: config
        run: |
          JAVA_VERSION=$(yq '.java.version' .github/config.yml)
          JAVA_DISTRIBUTION=$(yq '.java.distribution' .github/config.yml)
          echo "java-version=$JAVA_VERSION" >> $GITHUB_OUTPUT
          echo "java-distribution=$JAVA_DISTRIBUTION" >> $GITHUB_OUTPUT
      
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ steps.config.outputs.java-version }}
          distribution: ${{ steps.config.outputs.java-distribution }}
          cache: gradle
      
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      
      # Run Android Lint
      - name: Run Android Lint
        run: ./gradlew lint
      
      # Run Detekt (static code analysis)
      - name: Run Detekt
        run: |
          if ! grep -q "id(\"io.gitlab.arturbosch.detekt\")" build.gradle.kts; then
            echo "Adding Detekt plugin to build.gradle.kts"
            sed -i '/plugins {/a \    id("io.gitlab.arturbosch.detekt") version "1.23.1"' build.gradle.kts
          fi
          ./gradlew detekt
      
      # Run unit tests
      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest
      
      # Upload reports as artifacts
      - name: Upload analysis results
        uses: actions/upload-artifact@v3
        with:
          name: quality-reports
          path: |
            app/build/reports/lint-results*.html
            build/reports/detekt/
            app/build/reports/tests/
        if: always()
