name: Android CD

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version_name:
        description: 'Version name (e.g., 1.2.0)'
        required: true
      version_code:
        description: 'Version code (e.g., 120)'
        required: true
      release_notes:
        description: 'Release notes'
        required: false
        default: 'New release'

jobs:
  setup:
    uses: ./.github/workflows/reusable-android-setup.yml
  
  build-and-release:
    name: Build and Release APK
    needs: setup
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: gradle
      
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      
      - name: Update version (manual trigger)
        if: github.event_name == 'workflow_dispatch'
        run: |
          sed -i "s/versionCode = [0-9]*/versionCode = ${{ github.event.inputs.version_code }}/g" app/build.gradle.kts
          sed -i "s/versionName = \"[^\"]*\"/versionName = \"${{ github.event.inputs.version_name }}\"/g" app/build.gradle.kts
      
      - name: Build Debug APK
        run: ./gradlew assembleDebug
      
      - name: Upload APK
        uses: actions/upload-artifact@v4
        id: upload-apk
        with:
          name: TinyNotesManager-APK
          path: app/build/outputs/apk/debug/app-debug.apk
          compression-level: 0  # No compression for binary files
      
      - name: Create GitHub Release (from tag)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.upload-apk.outputs.artifact-path }}
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Create GitHub Release (manual)
        if: github.event_name == 'workflow_dispatch'
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.upload-apk.outputs.artifact-path }}
          tag_name: v${{ github.event.inputs.version_name }}
          name: Release v${{ github.event.inputs.version_name }}
          body: ${{ github.event.inputs.release_notes }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}