name: Android CI

on:
  push:
    branches:
      - '*'
      - '!master'
  pull_request:
    branches: [ master ]

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Load config
        id: config
        run: |
          JAVA_VERSION=$(yq '.java.version' .github/config.yml)
          JAVA_DISTRIBUTION=$(yq '.java.distribution' .github/config.yml)
          echo "java-version=$JAVA_VERSION" >> $GITHUB_OUTPUT
          echo "java-distribution=$JAVA_DISTRIBUTION" >> $GITHUB_OUTPUT
      
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ steps.config.outputs.java-version }}
          distribution: ${{ steps.config.outputs.java-distribution }}
          cache: gradle
      
      # Rest of your workflow...
